### ISSUE TITLE
tor hidden service

### ISSUE THREAD

**Issue by peterzen** [decred/cspp#30]
It would be nice to have `cspp.decred.org` accessible as a tor hidden service.  Are there any obstacles?

**Comment by jrick** [comment]
I believe a HS was already set up for the server, but I don't recall the address.  @dajohi?

**Comment by dajohi** [comment]
Need to add a flag to csppserver to specify the onion address.  and if specified, show a Tor section on the webpage

**Comment by peterzen** [comment]
#34 implements this

**Comment by jrick** [comment]
Merged.
